### ISSUE TITLE
Do you have an OpenIddict Flavor of this?

### ISSUE THREAD

**Issue by chrisjmccrum** [capesean/JWTKickStart#1]
Hey capesean, I was just wondering if you hooked this up to OpenIddict.  I'm trying to hook it up but i keep getin Cannot read property 'token' of null when GetToken is invoked.

**Comment by capesean** [comment]
Hi Chris

Does the [OpenIddict-Test](https://github.com/capesean/openiddict-test) not give you what you want?

I don't know if it's possible to mix OWIN with OpenIddict. I've just replaced my whole OWIN implementation (that was based on KWTKickStart) with a version of the OpenIddict - I'm not sure why you'd want to merge the two?

**Comment by chrisjmccrum** [comment]
I should've been a little more detailed. I'm not trying to mix the two.  I was referring to your login page and authentication service app flow.  Long story short, we've been using the default microsoft login pages and then we sent them to the angular app.  After a recent development meeting they wanted to see if we can just go pure angular on the login screen.  I then stumbled across your project and was trying to rewrite pieces of it to fit my OpenIddict Backend. Its proving harder than I thought it would be haha.

**Comment by capesean** [comment]
Hi Chris

Check out the OpenIddict-Test repo. I've updated it to include an AngularJS
login. I think that gives you what you want.

Regards
Sean
